sonar.projectKey=aurify-backend_Aurify-Wallet
sonar.organization=aurify-backend
sonar.projectName=Aurify-Wallet
sonar.sources=.
sonar.exclusions=**/guidelines/**
sonar.go.coverage.reportPaths=coverage.out